# Generated by Django 2.2.6 on 2019-11-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='支出分類マスタ',
            fields=[
                ('支出分類コード', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('支出分類名', models.CharField(blank=True, max_length=100, null=True)),
                ('項目名', models.CharField(blank=True, max_length=1, null=True)),
                ('削除フラグ', models.CharField(blank=True, default='0', max_length=1, null=True)),
            ],
        ),
    ]
