# Generated by Django 2.2.6 on 2019-11-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_支出分類マスタ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='支出分類マスタ',
            old_name='項目名',
            new_name='固定変動区分',
        ),
    ]
