# Generated by Django 2.2.6 on 2019-12-30 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_auto_20191117_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='対象者マスタ',
            fields=[
                ('対象者コード', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('対象者名', models.CharField(blank=True, max_length=100, null=True)),
                ('削除フラグ', models.CharField(blank=True, default='0', max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='支出明細',
            name='対象者コード',
            field=models.ForeignKey(blank=True, default='0000000000', null=True, on_delete=django.db.models.deletion.PROTECT, to='kakeibo.対象者マスタ'),
        ),
    ]
