# Generated by Django 2.2.6 on 2019-12-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0006_auto_20191230_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='支出基本',
            name='更新年月日',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='支出明細',
            name='更新年月日',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
