# Generated by Django 2.2.6 on 2019-12-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0007_auto_20191230_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='対象者マスタ',
            name='表示順序',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
