# Generated by Django 2.2.6 on 2019-12-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0008_対象者マスタ_表示順序'),
    ]

    operations = [
        migrations.AddField(
            model_name='支出分類マスタ',
            name='表示順序',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
