# Generated by Django 2.2.6 on 2019-12-30 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0009_支出分類マスタ_表示順序'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='支出分類マスタ',
            name='表示順序',
        ),
    ]
