# Generated by Django 2.2.6 on 2019-11-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_shisyutukihon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shisyutukihon',
            options={'managed': False},
        ),
    ]
