# Generated by Django 2.2.6 on 2020-01-12 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='定例支出マスタ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('開始年月', models.CharField(blank=True, default='000000', max_length=6, null=True)),
                ('終了年月', models.CharField(blank=True, default='999999', max_length=6, null=True)),
                ('有効月', models.CharField(blank=True, max_length=2, null=True)),
                ('金額', models.IntegerField(blank=True, null=True)),
                ('備考', models.CharField(blank=True, max_length=100, null=True)),
                ('作成年月日', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('更新年月日', models.DateTimeField(auto_now=True, null=True)),
                ('削除フラグ', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('対象者コード', models.ForeignKey(blank=True, default='0000000000', null=True, on_delete=django.db.models.deletion.PROTECT, to='kakeibo.対象者マスタ')),
                ('支出分類コード', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kakeibo.支出分類マスタ')),
            ],
        ),
    ]
