# Generated by Django 2.2.6 on 2020-01-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_定例支出マスタ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='定例支出マスタ',
            name='有効月',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
