# Generated by Django 2.2.6 on 2020-01-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_auto_20200112_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='支出分類マスタ',
            name='対象者区別有無',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
