# Generated by Django 2.2.6 on 2020-01-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_basemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
