# Generated by Django 2.2.6 on 2020-02-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0007_カード支出明細'),
    ]

    operations = [
        migrations.AlterField(
            model_name='カード支出明細',
            name='対象者コード',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kakeibo.対象者マスタ'),
        ),
    ]
