# Generated by Django 2.2.6 on 2020-02-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0009_auto_20200219_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='カード支出明細',
            old_name='支出分類コード',
            new_name='収入支出分類コード',
        ),
    ]
