# Generated by Django 2.2.6 on 2020-02-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0010_auto_20200219_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='定例支出マスタ',
            old_name='支出分類コード',
            new_name='収入支出分類コード',
        ),
    ]
